disabled_rules:
  - function_parameter_count
  - trailing_whitespace
  - shorthand_operator
  - nesting
opt_in_rules:
  - empty_count
  - private_outlet
line_length: 120
type_body_length:
  warning: 300
  error: 400
identifier_name:
  excluded:
    - to
    
cyclomatic_complexity:
  warning: 12
excluded:
  - Tests/
  - Carthage/
  - Frameworks/
  - Pods/