language: objective-c
os: osx
osx_image: xcode10

script:
- set -o pipefail 
- xcodebuild -workspace Reductio.xcworkspace -scheme Reductio -destination "platform=iOS Simulator,name=iPhone 7" -enableCodeCoverage YES clean build-for-testing test-without-building | xcpretty
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
